/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface CategoryItemProps {
  imageSrc: string;
  title: string;
}

const CategoryItem: React.FC<CategoryItemProps> = ({ imageSrc, title }) => {
  return (
    <div className="flex flex-col items-center">
      <div className="flex flex-col justify-center items-center px-2 bg-white rounded-full fill-white h-[118px] w-[118px]">
        <img
          loading="lazy"
          src={imageSrc}
          alt={title}
          className="object-contain rounded-lg aspect-square w-[104px]"
        />
      </div>
      <div className="self-center mt-2 text-lg font-medium text-center text-neutral-800">
        {title}
      </div>
    </div>
  );
};

export default CategoryItem;
