/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Sidebar from "./Sidebar";
import ProductList from "./ProductList";

const MainContent: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col items-center px-20 pt-52 bg-white pb-[548px] max-md:px-5 max-md:py-24">
      <div className="flex flex-col w-full max-w-[1680px] max-md:max-w-full">
        <Header />
        <div className="max-w-full w-[904px]">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-1/5 max-md:ml-0 max-md:w-full">
              <Sidebar />
            </div>
            <ProductList />
          </div>
        </div>
      </div>
    </main>
  );
};

export default MainContent;
