/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ProductCardProps {
  title: string;
  price: number;
  originalPrice: number;
  discount: number;
  unit: string;
  showQuantityControl?: boolean;
}

const ProductCard: React.FC<ProductCardProps> = ({
  title,
  price,
  originalPrice,
  discount,
  unit,
  showQuantityControl = false,
}) => {
  return (
    <article className="flex flex-col items-start px-4 pt-80 pb-4 w-full bg-white rounded-md border-solid shadow-sm border-[0.5px] border-zinc-300 max-md:pt-24 max-md:mt-9">
      <h3 className="self-stretch text-2xl font-medium leading-none text-neutral-800 max-md:mr-1.5">
        {title}
      </h3>
      <div className="flex gap-3.5 mt-10">
        <div className="grow text-2xl font-bold text-neutral-800">
          <span className="text-lg leading-6">QAR </span>
          {price.toFixed(2)}
        </div>
        <div className="text-lg leading-none text-neutral-400">
          {originalPrice.toFixed(2)}
        </div>
      </div>
      <div className="px-2 pt-1 pb-2.5 mt-3 text-lg font-semibold leading-none text-red-500 bg-red-100 rounded-sm">
        {discount}% OFF
      </div>
      <div className="mt-1.5 text-lg text-zinc-500">{unit}</div>
      {showQuantityControl ? (
        <div className="flex gap-5 justify-between self-end mt-6 max-w-full text-xl font-medium whitespace-nowrap bg-neutral-100 rounded-[48px] text-neutral-900 w-[215px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/9a034034f2ab58d91431e0f85ebf67e7f77f5c2f7067012d5482e29cc15c6fd1?placeholderIfAbsent=true&apiKey=9810db3822b54ab583e896edd833d595"
            alt=""
            className="object-contain shrink-0 rounded-none aspect-square w-[53px]"
          />
          <div className="my-auto">1</div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed73af3a0c374a7589ba503478bb8a33ad7e1a970124e2eaceee3c0bebc62cab?placeholderIfAbsent=true&apiKey=9810db3822b54ab583e896edd833d595"
            alt=""
            className="object-contain shrink-0 rounded-none aspect-[0.98] w-[52px]"
          />
        </div>
      ) : (
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4abbec96290731715993e4073053e785507848c3e9bac747f365c52396681611?placeholderIfAbsent=true&apiKey=9810db3822b54ab583e896edd833d595"
          alt=""
          className="object-contain self-end mt-6 rounded-none aspect-[0.98] w-[52px]"
        />
      )}
    </article>
  );
};

export default ProductCard;
