/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductCard from "./ProductCard";

const products = [
  {
    title: "Tomato Premium Import",
    price: 50.0,
    originalPrice: 80.0,
    discount: 40,
    unit: "Piece",
    showQuantityControl: true,
  },
  {
    title: "Goat Meat Whole\n(Smoke)",
    price: 50.0,
    originalPrice: 80.0,
    discount: 40,
    unit: "Piece",
    showQuantityControl: false,
  },
];

const ProductList: React.FC = () => {
  return (
    <section className="flex flex-col ml-5 w-4/5 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col mt-9 w-full max-md:mt-10 max-md:max-w-full">
        <div className="max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            {products.map((product, index) => (
              <div
                key={index}
                className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full"
              >
                <ProductCard {...product} />
              </div>
            ))}
          </div>
        </div>
        <div className="self-center mt-16 ml-20 text-sm font-semibold text-white max-md:mt-10">
          Best Seller
        </div>
      </div>
    </section>
  );
};

export default ProductList;
