/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductCard from "./ProductCard";
import { ProductData } from "./types";

const productsData: ProductData[] = [
  {
    id: 1,
    name: "Nat Fresh Chicken",
    price: 50.0,
    originalPrice: 80.0,
    unit: "Piece",
    discount: 40,
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a57a37934ddb3926e5f352f073486cb2732a16d153d9811df6bc10dcbbb51c44?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    quantity: 2,
  },
  {
    id: 2,
    name: "Goat Meat Whole (Smoke)",
    price: 50.0,
    originalPrice: 80.0,
    unit: "Piece",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/b592f15e-665c-451c-bc97-1e9ed44aa3e3?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    quantity: 1,
  },
  {
    id: 3,
    name: "Tomato Premium Import",
    price: 50.0,
    originalPrice: 80.0,
    unit: "Piece",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/adf5041f-6ba6-4aaa-832a-03b33f193001?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    quantity: 1,
  },
  {
    id: 4,
    name: "Goat Meat Whole (Smoke)",
    price: 50.0,
    originalPrice: 80.0,
    unit: "Piece",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a06da24b046f6c9723a62e24ebec2a83245b2e7390f6fe1203282e5b1108534a?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    quantity: 1,
  },
  {
    id: 5,
    name: "Tomato Premium Import",
    price: 50.0,
    originalPrice: 80.0,
    unit: "Piece",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/622d869c9007abb7bc07c8e06f48e1fd9f323700976ea5969b93ca8b5a5ec7e7?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    quantity: 1,
  },
  {
    id: 6,
    name: "Unnamed Product",
    price: 50.0,
    originalPrice: 80.0,
    unit: "Piece",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/5551d142-9050-4068-8b4a-4ed0ced0ae02?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    quantity: 1,
  },
  {
    id: 7,
    name: "Tomato Premium Import",
    price: 50.0,
    originalPrice: 80.0,
    unit: "Piece",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c1e26b48-d145-4c1c-8ada-f54a721de1f6?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    quantity: 2,
  },
];

const DealsOfTheDay: React.FC = () => {
  return (
    <section className="flex flex-col rounded-none max-w-[1680px] mx-auto mt-10">
      <h2 className="self-start text-4xl font-bold text-sky-800">
        Deals Of the Day
      </h2>
      <div className="mt-6 w-full max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {productsData.slice(0, 3).map((product) => (
            <ProductCard
              key={product.id}
              product={product}
              className="w-[33%] max-md:ml-0 max-md:w-full"
            />
          ))}
        </div>
      </div>
      <div className="mt-7 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {productsData.slice(3).map((product) => (
            <ProductCard
              key={product.id}
              product={product}
              className="w-3/12 max-md:ml-0 max-md:w-full"
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default DealsOfTheDay;
