/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { ProductData } from "./types";

interface ProductCardProps {
  product: ProductData;
  className?: string;
}

const ProductCard: React.FC<ProductCardProps> = ({ product, className }) => {
  return (
    <article className={`flex flex-col ${className}`}>
      <div className="grow pr-4 pb-2.5 w-full bg-white rounded-md shadow-sm max-md:mt-5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col text-xl font-bold text-white">
              {product.discount && (
                <div className="z-10 self-start px-7 py-1.5 bg-red-500 rounded-md max-md:px-5">
                  {product.discount}% OFF
                </div>
              )}
              <img
                loading="lazy"
                src={product.image}
                alt={product.name}
                className="object-contain mt-0 w-full aspect-square"
              />
            </div>
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow mt-7">
              <div className="flex flex-col px-1.5 w-full">
                <h3 className="text-2xl font-medium text-neutral-800">
                  {product.name}
                </h3>
                <div className="flex gap-3 mt-2 max-md:mr-2">
                  <div className="grow text-2xl text-neutral-800">
                    QAR {product.price.toFixed(2)}
                  </div>
                  <div className="my-auto text-lg text-neutral-400">
                    QAR {product.originalPrice.toFixed(2)}
                  </div>
                </div>
                <div className="self-start mt-1 text-lg text-zinc-500">
                  {product.unit}
                </div>
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/b244ff28099b49b386f985e96e05de322b6e1f427b7bc3c4f67ab2bd691e68fb?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                alt=""
                className="object-contain mt-14 max-w-full aspect-[4.76] w-[138px] max-md:mt-10"
              />
              <div className="self-end px-5 mt-11 text-3xl font-medium flex items-center justify-center text-white whitespace-nowrap bg-red-500 h-[58px] rounded-[29px] w-[58px] max-md:mt-10">
                {product.quantity}
              </div>
            </div>
          </div>
        </div>
      </div>
    </article>
  );
};

export default ProductCard;
