/**
 * This code was generated by Builder.io.
 */
export interface ProductData {
  id: number;
  name: string;
  price: number;
  originalPrice: number;
  unit: string;
  discount?: number;
  image: string;
  quantity: number;
}
