/**
 * This code was generated by Builder.io.
 */
import React from "react";

const DefaultAddress: React.FC = () => {
  return (
    <section
      className="flex flex-col px-5 py-9 mt-7 w-full bg-white rounded border border-gray-200 border-solid shadow-sm max-md:pl-5 max-md:max-w-full"
      style={{
        border: "1px solid #ECECEC",
        boxShadow: "2px 2px 2.5px 0px rgba(0, 0, 0, 0.16)",
      }}
    >
      <h2 className="self-start ml-3.5 text-2xl font-semibold text-neutral-800 max-md:ml-2.5">
        <span className="capitalize">Default Addre</span>ss
      </h2>
      <div className="px-3.5 py-4 mt-3.5 rounded-sm border border-solid border-zinc-100 shadow-[0px_0px_1px_rgba(0,0,0,0.161)] max-md:pr-5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col  max-md:ml-0 max-md:w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0e5fbc4621d8869acc215e7d10e93b96c1854d5878291bfbe42c7141eade7736?placeholderIfAbsent=true&apiKey=9810db3822b54ab583e896edd833d595"
              className="object-contain shrink-0 rounded aspect-square w-[90px] max-md:mt-8"
              alt="Address Icon"
            />
          </div>
          <div className="flex flex-col ml-5 w-4/5 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow mt-1 text-base font-medium rounded-none max-md:mt-9">
              <div className="leading-5 text-neutral-700">
                <span className="text-xl font-semibold text-neutral-800">
                  Home
                </span>
                <br />
                <span className="text-neutral-800">Abdullah Fahed</span>
                <br />
                Building 18, Alsadd 38, Street 50, Doha, Qatar
              </div>
              <div className="self-start mt-1.5 text-sky-800">
                +964 55773303
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DefaultAddress;
