/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HowItWorks: React.FC = () => {
  return (
    <div className="self-stretch mt-12 w-full max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="grow mt-7 max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              <div className="flex flex-col w-[43%] max-md:ml-0 max-md:w-full">
                <div className="flex relative flex-col grow items-center px-11 py-24 text-xs text-blue-300 whitespace-nowrap aspect-[1.088] w-[210px] max-md:px-5 max-md:mt-2.5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/1a32af092cb95f950cd19a021c926a0e5e551703bd44a92a7b80a84d85b017f3?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                    alt=""
                    className="object-cover absolute inset-0 size-full"
                  />
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[57%] max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/fbe7d0d3ea4524b66771023ea401056345dcfac77550f8280e9d7cf4eecf54d5?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                  alt=""
                  className="object-contain mt-3.5 aspect-[2.98] w-[280px] max-md:mt-6"
                />
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              <div className="flex flex-col w-[35%] max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/d9f0c0507497a1e4a52a5079d34d01db68277f43bae913020b274cc5dcf6284a?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                  alt=""
                  className="object-contain grow shrink-0 max-w-full aspect-[0.82] w-[165px] max-md:mt-3.5"
                />
              </div>
              <div className="flex flex-col ml-5 w-[65%] max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/850fe56f8abf09d2ee5986c55d0cbce765f6ca49be252a6321434b4144ccbefe?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                  alt=""
                  className="object-contain mt-24 aspect-[3.13] w-[306px] max-md:mt-10"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-wrap gap-5 justify-between self-start mt-7 ml-20 max-w-full text-lg text-sky-800 whitespace-nowrap w-[527px]">
        <div className="px-2.5 py-2 rounded-full shadow-[0px_3px_3px_rgba(0,0,0,0.161)]">
          01
        </div>
        <div className="px-2 py-2 rounded-full shadow-[0px_3px_3px_rgba(0,0,0,0.161)]">
          02
        </div>
      </div>
    </div>
  );
};

export default HowItWorks;
