/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ProductCardProps {
  name: string;
  price: number;
  originalPrice: number;
  discount: string;
  unit: string;
  image: string;
}

const ProductCard: React.FC<ProductCardProps> = ({
  name,
  price,
  originalPrice,
  discount,
  unit,
  image,
}) => {
  return (
    <article className="flex flex-col flex-1 py-3 bg-white rounded-md shadow-sm">
      <img
        loading="lazy"
        src={image}
        alt={name}
        className="object-contain max-w-full aspect-[1.09] w-[286px]"
      />
      <div className="flex flex-col items-start px-4 mt-3 w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d959b1d9f9ddf4196d02be6c352c0f5eda23be9bb466e6a80e20b0904f0242d0?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
          alt=""
          className="object-contain max-w-full aspect-[4.88] w-[132px]"
        />
        <h3 className="self-stretch mt-3 text-2xl font-medium leading-none text-neutral-800">
          {name}
        </h3>
        <div className="flex gap-3.5 mt-10">
          <div className="grow text-2xl font-bold text-neutral-800">
            <span className="text-lg leading-6 ">QAR </span> {price.toFixed(2)}
          </div>
          <div className="text-lg leading-none text-neutral-400">
            {originalPrice.toFixed(2)}
          </div>
        </div>
        <div className="px-2 pt-1 pb-2.5 mt-3 text-lg font-semibold leading-none text-red-500 bg-red-100 rounded-sm">
          {discount}
        </div>
        <div className="mt-1.5 text-lg text-zinc-500">{unit}</div>
        <div className="flex gap-5 justify-between self-end mt-6 max-w-full text-xl font-medium whitespace-nowrap bg-neutral-100 rounded-[48px] text-neutral-900 w-[215px] max-md:mr-1">
          <button
            aria-label="Decrease quantity"
            className="object-contain shrink-0 rounded-none aspect-square w-[53px]"
          >
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/1769d3f38f67e4ae8ac41db9e72968737dad7277ddf53d1408a85c926ceb3aa0?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt=""
              className="w-full h-full"
            />
          </button>
          <div className="my-auto">1</div>
          <button
            aria-label="Increase quantity"
            className="object-contain shrink-0 rounded-none aspect-[0.98] w-[52px]"
          >
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3f8f820821f48a5d0cf68672451c1912d677123af8aa61992b05be92a7c472c0?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt=""
              className="w-full h-full"
            />
          </button>
        </div>
      </div>
    </article>
  );
};

export default ProductCard;
