/**
 * This code was generated by Builder.io.
 */
import React from "react";

type CategoryCardProps = {
  image: string;
  title: string;
};

const CategoryCard: React.FC<CategoryCardProps> = ({ image, title }) => {
  return (
    <div className="flex flex-col items-center text-2xl font-semibold text-center whitespace-nowrap text-neutral-800">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="w-44 rounded-lg aspect-square"
      />
      <div className="mt-2.5">{title}</div>
    </div>
  );
};

export default CategoryCard;
