/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CategoryCard from "./CategoryCard";

type Category = {
  image: string;
  title: string;
};

type CategoryGridProps = {
  categories: Category[];
};

const CategoryGrid: React.FC<CategoryGridProps> = ({ categories }) => {
  return (
    <div className="flex gap-5 justify-between mt-16 w-full max-w-[1622px] max-md:flex-wrap max-md:mt-10 max-md:max-w-full">
      {categories.map((category, index) => (
        <CategoryCard key={index} {...category} />
      ))}
    </div>
  );
};

export default CategoryGrid;
