/**
 * This code was generated by Builder.io.
 */
import React from "react";

const DeliveryInfo: React.FC = () => {
  return (
    <>
      <div className="flex gap-2.5 self-stretch my-auto font-bold leading-5 text-white">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/549e2d02a24238a076781bc3e6b93c72c473806eae1a3aef02a356e8589eb3ab?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
          alt=""
          className="shrink-0 self-start aspect-[0.85] w-[30px]"
        />
        <div>
          <span className="text-white">Deliver to</span>
          <br /> Al Sadd, Qatar
        </div>
      </div>
      <div className="flex gap-2.5 items-start self-stretch my-auto font-medium text-white">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/678c9015849e86bf5ca51f54d7c10459b8cf71d1788ced0fa05e9ad4a4863395?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
          alt=""
          className="shrink-0 w-8 aspect-[1.03]"
        />
        <div className="flex-auto">Earliest Delivery</div>
      </div>
    </>
  );
};

export default DeliveryInfo;
