/**
 * This code was generated by Builder.io.
 */
import React from "react";

type FeatureCardProps = {
  icon: string;
  title: string;
  description: string;
  color: string;
};

const FeatureCard: React.FC<FeatureCardProps> = ({
  icon,
  title,
  description,
  color,
}) => {
  return (
    <div
      className={`flex grow gap-5 justify-between pr-4 w-full bg-white shadow-sm max-md:flex-wrap max-md:mt-10`}
    >
      <div className={`shrink-0 w-1 bg-${color}-800 h-[148px]`} />
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="shrink-0 my-auto aspect-square w-[54px]"
      />
      <div className="flex flex-col self-start mt-2.5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3bdd7ae948a4a1718e9624df98dd5a7b4692e5a357dc1156d1dd1927d2381cd2?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
          alt=""
          className="self-end aspect-square w-[21px]"
        />
        <div className={`mt-1.5 text-2xl font-semibold text-${color}-500`}>
          {title}
        </div>
        <div className="mt-4 text-lg font-medium leading-6 text-neutral-500">
          {description}
        </div>
      </div>
    </div>
  );
};

export default FeatureCard;
