/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col pt-12 w-full bg-slate-50 max-md:max-w-full">
      <div className="flex gap-5 justify-between items-start self-center px-5 max-w-full w-[1215px] max-md:flex-wrap">
        <div className="flex flex-col items-center self-end mt-12 max-md:mt-10 max-md:max-w-full">
          <div className="shrink-0 self-stretch h-px border border-sky-500 border-solid max-md:max-w-full" />
          <h3 className="mt-11 text-2xl font-bold text-center text-black max-md:mt-10">
            Quick Link
          </h3>
          <nav>
            <ul>
              <li className="mt-6 text-lg font-medium text-center text-neutral-700">
                Home
              </li>
              <li className="mt-6 text-lg font-medium text-center text-neutral-700">
                About us
              </li>
              <li className="mt-6 text-lg font-medium text-center text-neutral-700">
                Contact us
              </li>
            </ul>
          </nav>
          <div className="flex gap-2 mt-20 max-w-full w-[272px] max-md:mt-10">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ee8fefbd02f6b5f71632374fa675323e71520489aa3af89d4f0a83a30e309179?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt="App Store"
              className="shrink-0 max-w-full aspect-[3.33] w-[132px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/354d9a40d6584edf38e49f98eb53629ea1b797fb17543b9296b8335e20904713?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt="Google Play"
              className="shrink-0 max-w-full aspect-[3.45] w-[133px]"
            />
          </div>
          <div className="flex gap-5 justify-between px-4 py-3.5 mt-2.5 max-w-full font-medium text-center bg-sky-900 rounded w-[272px]">
            <div className="text-sm leading-4 text-white">
              <span className="text-white">We're alwa</span>ys <br /> here to
              help!
            </div>
            <div className="flex gap-3 self-start text-xl text-white whitespace-nowrap">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/07ba7ba8c24aa3f7fa4af61c1829cc3be04b5b0efce4f4c63f0909196cb0e3e6?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                alt=""
                className="shrink-0 aspect-[1.04] w-[26px]"
              />
              <div className="my-auto">2688790</div>
            </div>
          </div>
        </div>
        <div className="flex flex-col self-start">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/eb396800b52890f9a4904a2dd98f8260f836372f5307e909fa1982f0bb40b7bd?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
            alt="Company Logo"
            className="self-center max-w-full aspect-[1.82] w-[110px]"
          />
          <div className="flex gap-5 justify-between items-start mt-11 max-md:mt-10">
            <a href="#" aria-label="Facebook">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed246916d6ad0ed1702aafef6f8daa5881020817421a2296c1d0f1e3f0ed31a2?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                alt=""
                className="shrink-0 self-stretch aspect-[0.45] w-[13px]"
              />
            </a>
            <a href="#" aria-label="Twitter">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/c010296f17ec764c7eca7e4a934ffc9d402e3fdf82c1c4d81357020e81c361aa?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                alt=""
                className="shrink-0 mt-2.5 aspect-[1.25] w-[25px]"
              />
            </a>
            <a href="#" aria-label="Instagram">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/a8827761fba08d9651cd3af62355d9376f54643fd5f624cda18983ce83ff5cb0?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                alt=""
                className="shrink-0 mt-1.5 w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="LinkedIn">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3f734810f237072db469fb402c3186ec6755ee56a9aa08e9c587949992a6db2d?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
                alt=""
                className="shrink-0 mt-2 aspect-square w-[21px]"
              />
            </a>
          </div>
        </div>
        <div className="flex flex-col items-center my-auto text-lg font-medium text-neutral-700 max-md:max-w-full">
          <div className="shrink-0 self-stretch h-px border border-sky-500 border-solid max-md:max-w-full" />
          <h3 className="mt-11 text-2xl font-bold text-center text-black max-md:mt-10">
            Policies
          </h3>
          <nav>
            <ul>
              <li className="mt-9">Terms & Conditions</li>
              <li className="mt-6">Return Policy</li>
              <li className="mt-5">Website Accessibility</li>
              <li className="mt-5">Privacy Policy</li>
              <li className="mt-5">Service and Warranty</li>
            </ul>
          </nav>
        </div>
      </div>
      <div className="flex justify-center items-center px-16 py-3.5 mt-10 w-full bg-neutral-100 shadow-[0px_-1px_1px_rgba(0,0,0,0.161)] max-md:px-5 max-md:max-w-full">
        <div className="flex gap-5 w-full max-w-[1649px] max-md:flex-wrap max-md:max-w-full">
          <div className="flex-auto my-auto text-sm font-medium text-zinc-400">
            <span className="capitalize">2023 W</span>idam all right reserved
          </div>
          <div className="flex gap-5 justify-between items-start text-2xl font-semibold text-sky-900 whitespace-nowrap">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/721d945938c14c4316bee55ff7dec833b4f4966dfdcd6dcee540117406290e68?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt="Payment Method 1"
              className="shrink-0 my-auto w-20 aspect-[3.03]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7ed261ef0a759c2d49039257a1f7b04339850c4625369d49e7b1e9d187fb4dea?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt="Payment Method 2"
              className="shrink-0 self-start aspect-[1.79] w-[50px]"
            />
            <div className="my-auto">Cash</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/a4060590f06773b83ed6d13045499364934b06ac1c0ca9b462387f69211d0727?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt="Payment Method 3"
              className="shrink-0 self-start aspect-[2.33] w-[63px]"
            />
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
