/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";
import DeliveryInfo from "./DeliveryInfo";
import UserActions from "./UserActions";

type HeaderProps = {
  logo: string;
  cartTotal: string;
};

const Header: React.FC<HeaderProps> = ({ logo, cartTotal }) => {
  return (
    <header className="flex justify-center items-center px-16 py-6 w-full bg-sky-500 max-md:px-5 max-md:max-w-full">
      <div className="flex gap-5 justify-between w-full max-w-[1659px] max-md:flex-wrap max-md:max-w-full">
        <div className="flex gap-4 justify-between items-center text-base max-md:flex-wrap max-md:max-w-full">
          <img
            loading="lazy"
            src={logo}
            alt="Company Logo"
            className="shrink-0 self-stretch my-auto aspect-[1.85] w-[68px]"
          />
          <SearchBar />
          <DeliveryInfo />
        </div>
        <UserActions cartTotal={cartTotal} />
      </div>
    </header>
  );
};

export default Header;
