/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Navigation from "./Navigation";
import Footer from "./Footer";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex flex-col bg-white">
      <Header
        logo="https://cdn.builder.io/api/v1/image/assets/TEMP/ddb7b89cdf5a5717478db868d6a33eca92a94829276d4d56cae4fe6a0fe03ddb?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
        cartTotal="QAR 115.00"
      />
      <Navigation />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
