/**
 * This code was generated by Builder.io.
 */
import React from "react";

const categories = [
  "All Category",
  "Meat and Chicken",
  "Fresh Fruits",
  "Fresh Vegetables",
  "Spices",
  "Local products",
];

const Navigation: React.FC = () => {
  return (
    <nav className="flex flex-col items-center px-16 pt-6 pb-12 w-full bg-neutral-100 shadow-[0px_0px_2px_rgba(0,0,0,0.161)] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col w-full max-w-[1680px] max-md:max-w-full">
        <div className="flex gap-5 justify-between w-full max-md:flex-wrap max-md:max-w-full">
          <div className="flex gap-5 my-auto max-md:flex-wrap max-md:max-w-full">
            <div className="flex flex-col my-auto">
              <div className="shrink-0 bg-sky-900 rounded-sm border border-sky-900 border-solid h-[3px]" />
              <div className="shrink-0 bg-sky-900 rounded-sm border border-sky-900 border-solid h-[3px]" />
            </div>
            {categories.map((category, index) => (
              <div
                key={index}
                className="flex-auto text-xl font-semibold text-sky-900 capitalize"
              >
                {category}
              </div>
            ))}
          </div>
          <div className="flex gap-5 justify-between">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8e9566bbbdcfafcbe746af0cc60580a903a780ae7e042f99d1d6514585994820?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt=""
              className="shrink-0 aspect-[0.43] w-[13px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/406e35f61509d44e3477da4f22b8b6cad9ee7f9f86cfd315b6d0fe7283e15f00?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt=""
              className="shrink-0 self-start mt-2 aspect-[1.18] w-[26px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/1a051073822eab09330608f04e91bc8dc5382278af098e177c4c4192c83dc460?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt=""
              className="shrink-0 my-auto aspect-square w-[25px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e8145b8f908a66c1df3adcb74a8578d9f90310879527dee073bb25d13c8d97d0?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
              alt=""
              className="shrink-0 self-start mt-2 aspect-square w-[22px]"
            />
          </div>
        </div>
        <div className="shrink-0 mt-6 ml-12 h-0.5 bg-white rounded-sm border border-sky-900 border-solid w-[187px] max-md:ml-2.5" />
      </div>
    </nav>
  );
};

export default Navigation;
