/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductCard from "./ProductCard";

type Product = {
  image: string;
  title: string;
  price: string;
  originalPrice: string;
  discount: string;
  unit: string;
};

type ProductGridProps = {
  title: string;
  products: Product[];
};

const ProductGrid: React.FC<ProductGridProps> = ({ title, products }) => {
  return (
    <section className="flex flex-col items-center self-center px-5 mt-9 w-full max-w-[1716px] max-md:max-w-full">
      <h2 className="self-start text-4xl font-bold text-sky-800">{title}</h2>
      <div className="mt-6 w-full max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {products.map((product, index) => (
            <ProductCard key={index} {...product} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default ProductGrid;
