/**
 * This code was generated by Builder.io.
 */
import React from "react";

type ProductCardProps = {
  image: string;
  title: string;
  price: string;
  originalPrice: string;
  discount: string;
  unit: string;
};

const ProductCard: React.FC<ProductCardProps> = ({
  image,
  title,
  price,
  originalPrice,
  discount,
  unit,
}) => {
  return (
    <div className="flex flex-col flex-1 py-3 bg-white rounded-md border border-solid shadow-sm border-zinc-300">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="self-start w-full aspect-[1.11]"
      />
      <div className="flex flex-col px-4 mt-3">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d959b1d9f9ddf4196d02be6c352c0f5eda23be9bb466e6a80e20b0904f0242d0?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
          alt=""
          className="max-w-full aspect-[5] w-[132px]"
        />
        <div className="mt-4 text-2xl font-medium text-neutral-800">
          {title}
        </div>
        <div className="flex gap-4 mt-11 max-md:mt-10">
          <div className="grow text-2xl font-bold text-neutral-800">
            <span className="text-lg leading-6">QAR </span>
            {price}
          </div>
          <div className="flex-auto text-lg text-neutral-400">
            {originalPrice}
          </div>
        </div>
        <div className="px-2 py-2.5 mt-3.5 text-lg font-semibold text-red-500 bg-red-100 rounded-sm">
          {discount} OFF
        </div>
        <div className="mt-2.5 text-lg text-zinc-500">{unit}</div>
        <div className="flex gap-5 justify-between self-end mt-8 max-w-full text-xl font-medium whitespace-nowrap bg-neutral-100 rounded-[48px] text-neutral-900 w-[215px]">
          <button
            aria-label="Decrease quantity"
            className="shrink-0 rounded-none aspect-square w-[53px]"
          >
            -
          </button>
          <div className="my-auto">1</div>
          <button
            aria-label="Increase quantity"
            className="shrink-0 rounded-none aspect-[0.98] w-[52px]"
          >
            +
          </button>
        </div>
      </div>
    </div>
  );
};

export default ProductCard;
