/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchBar: React.FC = () => {
  return (
    <div className="flex gap-3.5 self-stretch px-6 py-3.5 text-lg bg-white rounded-md text-neutral-700 max-md:flex-wrap max-md:px-5">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/81b2f047cf95a2b27eedd4440eb275b711a31d15818ccab3e6a507c762c8c470?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
        alt=""
        className="shrink-0 w-6 aspect-[1.04]"
      />
      <input
        type="text"
        placeholder="Search for any product"
        className="flex-auto max-md:max-w-full"
        aria-label="Search for any product"
      />
    </div>
  );
};

export default SearchBar;
