/**
 * This code was generated by Builder.io.
 */
import React from "react";

type UserActionsProps = {
  cartTotal: string;
};

const UserActions: React.FC<UserActionsProps> = ({ cartTotal }) => {
  return (
    <div className="flex gap-3 self-start mt-1.5 text-sm font-semibold text-white">
      <div className="grow my-auto">{cartTotal}</div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e000b72a-cc0e-49f4-9d61-07dde9f24391?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
        alt="User profile"
        className="shrink-0 bg-white rounded-full aspect-[0.95] h-[41px] w-[41px]"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/548f438b-61f0-4531-a250-23bee195294f?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
        alt="Shopping cart"
        className="shrink-0 self-start mt-1 bg-white rounded-full aspect-square h-[38px] w-[38px]"
      />
    </div>
  );
};

export default UserActions;
