/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface AddToCartButtonProps {
  price: number;
}

const AddToCartButton: React.FC<AddToCartButtonProps> = ({ price }) => {
  return (
    <button className="flex flex-auto gap-3.5 px-14 py-4 font-bold bg-[#05B] rounded max-md:px-5 max-w-[378px] max-md:max-w-full">
      <div className="grow text-2xl text-white capitalize">Add To Cart</div>
      <div className="my-auto text-lg text-white">QAR {price.toFixed(2)}</div>
    </button>
  );
};

export default AddToCartButton;
