/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface CuttingOptionProps {
  image: string;
  label: string;
}

const CuttingOption: React.FC<CuttingOptionProps> = ({ image, label }) => {
  return (
    <div className="flex flex-col flex-1 px-5 pt-1.5 pb-3 whitespace-nowrap rounded border border-solid border-zinc-400">
      <img
        loading="lazy"
        src={image}
        alt={`${label} cutting option`}
        className="object-contain aspect-[1.08] w-[108px]"
      />
      <div className="self-center">{label}</div>
    </div>
  );
};

export default CuttingOption;
