/**
 * This code was generated by Builder.io.
 */
import React from "react";

const BrowseAllBanner: React.FC = () => {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/86a36558934c817ff7fca655f34c7f7a724d7438a55fc1609eecf6b7f0029978?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595"
      alt="Browse All Categories Banner"
      className="object-contain mt-14 w-full rounded-none aspect-[3.53] max-md:mt-10 max-md:max-w-full"
    />
  );
};

export default BrowseAllBanner;
