/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CategoryItem from "./CategoryItem";
import MeatCategory from "./MeatCategory";
import BrowseAllBanner from "./BrowseAllBanner";
import MeetCategory from "../MeatCategory/MeatCategoryPage";
import ShopByCategory from "../ShopByCategory";

interface ShopByCategoryProps {}

const ShopByCategorySection: React.FC<ShopByCategoryProps> = () => {
  const categories = [
    {
      name: "Meat",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/4b5d49eb55014a505b0159eebbc9b1fd60d7b1e72aaa14896c1bb64464c26973?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "indian",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/6b4d735ddfca6fb17bab455ec20b459176a8a19fd116b34966fd6a00386eb55e?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Fresh Vegetables",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/3a777523e093f25882bac9ba4186e2315e007c95d353b81234c423ebde14db2e?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Juice",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/c24a11c0-9001-47e6-a96b-9f9c3d987985?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Spices",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/a84c9188-d2b1-492b-b0f7-66e5979c466c?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Fresh Fruits",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/0f992a7f-076f-4c81-aa4c-a12ad0a2b8c3?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Local Products",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1053ffa72cce2f0413f82b0fedfaed3a0faad6f46cf873414695673369cf8696?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "View All Categories",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/caf8d92002c3882d966b83ad99a2e8c3e1b7a9a79e43c88b1cdaf8c0e1462b97?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
  ];

  const meatCategories = [
    {
      name: "camel meat",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/494f2717af1aa6407b009662907c5dbb678698e20cb954783fe2022ec2a15511?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Beef Meat",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/8e855063-f839-4af6-a3bd-519fdc7df6bd?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Lamb meat",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/645b50d2bc0016b883f305b1b486b70ffcdb56400cf0d3a07cfbaad77b2a5573?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "chicken",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/d7f015fa4886caa9b694ab317a78b1b2fc3a7ec6fe04aa2dc6ad1bbac91ce7fa?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "camel meat",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/3e976963c6cafe5e2fcdfede59719de7e5051b4d63f060ff052316aea6f08b48?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Beef Meat",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/494f2717af1aa6407b009662907c5dbb678698e20cb954783fe2022ec2a15511?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Lamb meat",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ee5ba0a8-b548-4f5a-baf2-8d4cc29dad3c?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
    {
      name: "Aqeeqah",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/8ff75c4c95aa142872d650c0b105d2a13f9097466d57c3f526103e2153a44581?apiKey=9810db3822b54ab583e896edd833d595&&apiKey=9810db3822b54ab583e896edd833d595",
    },
  ];

  return (
    <section className="flex flex-col px-20 pb-12 rounded-none max-md:px-5 mt-10">
      <div className="flex flex-col self-end w-full max-w-[1716px] mx-auto max-md:max-w-full">
        <ShopByCategory />
        <BrowseAllBanner />
      </div>
    </section>
  );
};

export default ShopByCategorySection;
