/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface MeatCategoryItemProps {
  name: string;
  imageSrc: string;
  imageClass: string;
}

const MeatCategoryItem: React.FC<MeatCategoryItemProps> = ({
  name,
  imageSrc,
  imageClass,
}) => {
  return (
    <div className="flex flex-col text-3xl font-semibold text-center text-neutral-800">
      <img
        loading="lazy"
        src={imageSrc}
        alt={`${name} category`}
        className={imageClass}
      />
      <div className="mt-1.5">{name}</div>
    </div>
  );
};

export default MeatCategoryItem;
